# SPDX-FileCopyrightText: <text>Copyright 2026 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: Apache-2.0

CONFIG_NET_ZPERF=y
CONFIG_SHELL=y
CONFIG_NET_VLAN=y
CONFIG_NET_SHELL=y
CONFIG_NET_STATISTICS=y
