# SPDX-FileCopyrightText: <text>Copyright 2026 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: Apache-2.0

# PFDI Agent - Enable MBOX (mailbox) for MHUv3
CONFIG_MBOX=y
CONFIG_MBOX_MHUV3=y

# PFDI Agent subsystem
CONFIG_PFDI_AGENT=y
CONFIG_PLAT_PFDI_POST_RUN_HOOK=y
CONFIG_PFDI_AGENT_LOG_LEVEL_INF=y
CONFIG_MBOX_LOG_LEVEL_ERR=y

CONFIG_LOG_MODE_DEFERRED=y
