# SPDX-FileCopyrightText: <text>Copyright 2026 Arm Limited and/or its
# affiliates <open-source-office@arm.com></text>
#
# SPDX-License-Identifier: Apache-2.0

CONFIG_PFDI_MODULE=y
CONFIG_PFDI_MGMT=y

#Stub firmware integrated for demo purposes;
#override with actual firmware metadata when available
CONFIG_PFDI_FW_METADATA=0x00000000

CONFIG_SOC_PER_CORE_INIT_HOOK=y
CONFIG_SCHED_CPU_MASK=y
CONFIG_PFDI_MGMT_THREAD_STACK_SIZE=4096
CONFIG_PFDI_MGMT_DEBUG=y

CONFIG_SHELL_HELP=y
CONFIG_SHELL=y

CONFIG_LOG=y
CONFIG_LOG_PRINTK=n

CONFIG_SHELL_TAB=y
CONFIG_SHELL_TAB_AUTOCOMPLETION=y
